{% set name = "aws-cdk.assets" %}
{% set version = "1.204.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws-cdk.assets-{{ version }}.tar.gz
  sha256: 10d320ac17a60e9989869c7ae8a25f4ff3f8458bf2689cfba4a7050de019933f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >=3.7
    - aws-cdk.core ==1.204.0
    - aws-cdk.cx-api ==1.204.0
    - constructs >=3.3.69,<4.0.0
    - python-jsii >=1.84.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0

test:
  imports:
    - aws_cdk.assets
    - aws_cdk.assets._jsii
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-cdk
  summary: This module is deprecated. All types are now available under the core module
  dev_url: https://github.com/aws/aws-cdk.git
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
